// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OndatoCacheSolution.Infrastructure;

namespace OndatoCacheSolution.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OndatoCacheSolution.Infrastructure.Entities.DbCacheKey", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeSpan>("ExpiresAfter")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("LastRefreshed")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Key");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("OndatoCacheSolution.Infrastructure.Entities.DbCacheValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KeyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KeyId");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("OndatoCacheSolution.Infrastructure.Entities.DbCacheValue", b =>
                {
                    b.HasOne("OndatoCacheSolution.Infrastructure.Entities.DbCacheKey", "Key")
                        .WithMany("Values")
                        .HasForeignKey("KeyId");

                    b.Navigation("Key");
                });

            modelBuilder.Entity("OndatoCacheSolution.Infrastructure.Entities.DbCacheKey", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
